<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.3</version>
		<relativePath/>
	</parent>
	<groupId>org.settlehub.commons</groupId>
	<artifactId>health</artifactId>
	<version>0.0.1-DEV</version>
	<name>health-common</name>
	<description>Health Check Library with a Simple Annotation</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
			<developer>
					<id>karakay-v</id>
					<name>Vladyslav Karakai</name>
					<email>hitechnic00074220@gmail.com</email>
					<url>https://karakay-v.github.io</url>
					<organization>SettleHub</organization>
					<organizationUrl>https://github.com/settlehub</organizationUrl>
					<roles>
							<role>architect</role>
							<role>developer</role>
					</roles>
					<timezone>Europe/Kyiv</timezone>
					<properties>
							<picUrl>https://avatars.githubusercontent.com/u/113354711?v=4</picUrl>
					</properties>
			</developer>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>21</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<scope>provided</scope> 
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
    </dependencies>
	<distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub SettleHub Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/SettleHub/health-common</url>
        </repository>
    </distributionManagement>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
